# Generated by Django 4.1.4 on 2022-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empresa_alter_produto_options_remove_produto_estoque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
