# Generated by Django 4.1.4 on 2022-12-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_clients_company_companyowner_product_transations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyowner',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='app.company'),
        ),
    ]
